export const GET_INITITAL_IMAGES = "GET_INITITAL_IMAGES";
export const GET_SEARCH_IMAGES = "GET_SEARCH_IMAGES";
export const SET_INITIAL_IMAGES = "SET_INITIAL_IMAGES";
export const SET_SEARCH_IMAGES = "SET_SEARCH_IMAGES";
export const GET_SEARCH_NEXT_IMAGES = "GET_SEARCH_NEXT_IMAGES";
export const SET_SEARCH_NEXT_IMAGES = "SET_SEARCH_NEXT_IMAGES";
